### ISSUE TITLE
输出都是_UNK

### ISSUE THREAD

**Issue by DavidDota** [thunlp/TensorFlow-Summarization#3]
输出都是_UNK  词表用的也是自己生成的，生成一篇摘要，90%都是_UNK是什么原因呢？ 训练5万条数据对，困惑度到了70多  一万step

**Comment by leopard1** [comment]
感觉主要问题是数据比较少，我训练的时候数据有300万条，训练轮数大概要到20万轮才能有比较好的效果，困惑度大约30。

祝好！

**Comment by DavidDota** [comment]
嗯，还有就是我是做的中文摘要，只是对编码部分稍作修改，应该不是这方面的问题吧？

**Comment by leopard1** [comment]
输入文件使用UTF8编码，分词用空格隔开（也可以做字级别的模型，每个字用空格隔开），代码不需要修改，python3天然可以比较好的支持中文。

**Comment by DavidDota** [comment]
嗯，是的，我就是这样的，那导致输出都是unk的原因估计就是训练集和训练轮次了
