### ISSUE TITLE
Is there a demo to check the efficiency?

### ISSUE THREAD

**Issue by JafferWilson** [thunlp/TensorFlow-Summarization#4]
I have been working on the Tensorflow summarization and tried it using 8 GPUs. Even for training for 1 month I was getting the <unk>'s in the result. I would like to know whether your repository gives proper result or not? and what is the efficiency of the repository for summarization.
Kindly, let me know where I can see the demo.

**Comment by leopard1** [comment]
Hi, I did not try the code on multiple GPUs. I used one GTX Titan and trained 300,000 batches. Please check [here](sfo.citr.me/static) for trained models.
