### ISSUE TITLE
是否支持中文或者其他语言

### ISSUE THREAD

**Issue by carrotW** [thunlp/TensorFlow-Summarization#6]
这个模型是否可以不加修改的，在非英语的环境下训练？ 比如使用微博数据训练

**Comment by luzhaofeng** [comment]
请问该模型是否支持中文

**Comment by leopard1** [comment]
python3对中文有很好的支持，对于中文的数据，使用utf8编码可以进行训练。
如果使用词级别的模型，请使用分词工具处理。
使用字级别的模型，请用空格将每个字隔开。
