### ISSUE TITLE
Placement of dataset

### ISSUE THREAD

**Issue by xtknight** [thunlp/TensorFlow-Summarization#7]
Hello,

I managed to run training with train.article.txt and train.title.txt but now I'm confused about how to get the test data sets setup properly. 

The paths are shown below, but how am I supposed to convert these into  a data/test.duc2004.txt  which is being loaded by the test script?  What exactly is supposed to be in this single file?

data/DUC2004/task1_ref0.txt
data/DUC2004/task1_ref1.txt
data/DUC2004/task1_ref3.txt
data/DUC2004/task1_ref2.txt
data/DUC2004/input.txt

**Comment by leopard1** [comment]
test.duc2004.txt is actually data/DUC2004/input.txt. Other files in data/DUC2004 are annotated summaries for ROUGE evaluation.
